export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_PERMISSION = "LOGIN_USER_PERMISSION";
export const LOGIN_USER_ROLE = "LOGIN_USER_ROLE";
export const LOGIN_USER_MEMBER = "LOGIN_USER_MEMBER";
export const LOGIN_USER_SUPER_ADMIN = "LOGIN_USER_SUPER_ADMIN";


